#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x08302DB6A2670428 (tim.ruehsen@gmx.de)
#
Name     : libidn2
Version  : 2.0.1
Release  : 1
URL      : https://ftp.gnu.org/gnu/libidn/libidn2-2.0.1.tar.xz
Source0  : https://ftp.gnu.org/gnu/libidn/libidn2-2.0.1.tar.xz
Source99 : https://ftp.gnu.org/gnu/libidn/libidn2-2.0.1.tar.xz.sig
Summary  : Library implementing IDNA2008 and TR46
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 LGPL-3.0 Unicode-TOU
Requires: libidn2-bin
Requires: libidn2-lib
Requires: libidn2-doc
BuildRequires : docbook-xml
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin

%description
[![build status](https://gitlab.com/libidn/libidn2/badges/master/build.svg)](https://gitlab.com/libidn/libidn2/pipelines)
[![coverage status](https://gitlab.com/libidn/libidn2/badges/master/coverage.svg)](https://libidn.gitlab.io/libidn2/coverage)
[![Coverity Scan Build Status](https://scan.coverity.com/projects/12080/badge.svg)](https://scan.coverity.com/projects/libidn2)

%package bin
Summary: bin components for the libidn2 package.
Group: Binaries

%description bin
bin components for the libidn2 package.


%package dev
Summary: dev components for the libidn2 package.
Group: Development
Requires: libidn2-lib
Requires: libidn2-bin
Provides: libidn2-devel

%description dev
dev components for the libidn2 package.


%package doc
Summary: doc components for the libidn2 package.
Group: Documentation

%description doc
doc components for the libidn2 package.


%package lib
Summary: lib components for the libidn2 package.
Group: Libraries

%description lib
lib components for the libidn2 package.


%prep
%setup -q -n libidn2-2.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1492959304
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1492959304
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/idn2

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libidn2.so
/usr/lib64/pkgconfig/libidn2.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*
/usr/share/gtk-doc/html/libidn2/api-index-full.html
/usr/share/gtk-doc/html/libidn2/home.png
/usr/share/gtk-doc/html/libidn2/index.html
/usr/share/gtk-doc/html/libidn2/left-insensitive.png
/usr/share/gtk-doc/html/libidn2/left.png
/usr/share/gtk-doc/html/libidn2/libidn2-idn2.html
/usr/share/gtk-doc/html/libidn2/libidn2.devhelp2
/usr/share/gtk-doc/html/libidn2/libidn2.html
/usr/share/gtk-doc/html/libidn2/right-insensitive.png
/usr/share/gtk-doc/html/libidn2/right.png
/usr/share/gtk-doc/html/libidn2/style.css
/usr/share/gtk-doc/html/libidn2/up-insensitive.png
/usr/share/gtk-doc/html/libidn2/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libidn2.so.0
/usr/lib64/libidn2.so.0.3.0
